Traceback (most recent call last):
  File "/home/sandeep/Documents/IITM/Deep Learning/main.py", line 29, in <module>
    image = wandb.Image(images,caption = f'caption_{i}')
  File "/home/sandeep/.local/lib/python3.10/site-packages/wandb/sdk/data_types/image.py", line 179, in __init__
    self._initialize_from_data(data_or_path, mode, file_type)
  File "/home/sandeep/.local/lib/python3.10/site-packages/wandb/sdk/data_types/image.py", line 321, in _initialize_from_data
    if data.ndim > 2:
AttributeError: 'list' object has no attribute 'ndim'
Traceback (most recent call last):
  File "/home/sandeep/Documents/IITM/Deep Learning/main.py", line 29, in <module>
    image = wandb.Image(images,caption = f'caption_{i}')
  File "/home/sandeep/.local/lib/python3.10/site-packages/wandb/sdk/data_types/image.py", line 179, in __init__
    self._initialize_from_data(data_or_path, mode, file_type)
  File "/home/sandeep/.local/lib/python3.10/site-packages/wandb/sdk/data_types/image.py", line 321, in _initialize_from_data
    if data.ndim > 2:
AttributeError: 'list' object has no attribute 'ndim'